version: "3.7"

services:
  app:
    image: node:20-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /to-do-app
    volumes:
      - ./:/to-do-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Qq123456
      MYSQL_DB: todos
      
  mysql:
    image: mysql:5.7
    volumes:
      - to-do-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Qq123456
      MYSQL_DATABASE: todos

volumes:
  to-do-mysql-data: